### ISSUE TITLE
R-Libraries for UDFs that user needs

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-udf-python-to-r#10]
We still need to define how a user can specify the libraries he needs for his UDFs (probably difficult due to security issues at the backend). At least the user should be able to querry the libs that are available within the UDF service.

**Comment by m-mohr** [comment]
That is actually already possible. GET /udf_runtimes will expose that, but of course the back-end needs to implement that the API response is complete. So I don't think that is our task....
