### ISSUE TITLE
Parallelizing as currently foreseen doesn't work!

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-udf-python-to-r#12]
The parallelization has to be [done before the call to Rpy2](https://github.com/joblib/joblib/issues/762) otherwise it will a) fail (we have tested that) or b) we need [thread locking](https://rpy2.github.io/doc/v3.3.x/html/rinterface.html#multithreading) to force the R execution in series (not parallel, also tested).

This needs more investigation on Rpy2. Maybe check the issues of the package and the most recent developments.
https://github.com/rpy2/rpy2/issues/582
https://github.com/rpy2/rpy2/issues/585

for example:
```
pzellner@eosao52:~/git_projects/openeo-udf-python-to-r$ python demo.py
reduce_dimension bfast
start:  ./udfs/reduce_bfast.R
/home/pzellner@eurac.edu/.conda/envs/udf_env/lib/python3.7/site-packages/rpy2/rinterface.py:961: UserWarning: R is not initialized by the main thread.
                Its taking over SIGINT cannot be reversed here, and as a
                consequence the embedded R cannot be interrupted with Ctrl-C.
                Consider (re)setting the signal handler of your choice from
                the main thread.
  the main thread."""
R[write to console]: Error: promise already under evaluation: recursive default argument reference or earlier problems?

R[write to console]: Warning: stack imbalance in 'lazyLoadDBfetch', 1 then -2

R[write to console]: Error in .signalSimpleWarning("restarting interrupted promise evaluation",  : 
  unused arguments ("restarting interrupted promise evaluation", base::quote(getNamespace("compiler")))

R[write to console]: Warning: stack imbalance in ':::', 9 then 10

*** longjmp causes uninitialized stack frame ***: python terminated
Aborted (core dumped)
```

**Comment by przell** [comment]
@m-mohr 
some more interesting links on how to parallelize RPy2

**Multithreading is discouraged for RPy2... there are alternatives mentioned:**
https://stackoverflow.com/questions/42015044/what-is-the-most-efficient-way-to-parallelize-python-code-that-uses-rpy2


⚠️  **Notebook for parallelising Rpy2 from the Package Developer:**
https://twitter.com/lgautier/status/1213251450593316869
https://github.com/rpy2/rpy2/blob/master/doc/_static/demos/multiproc_lab.py

**This I don't really understand**
https://notebook.community/knowledgeanyhow/notebooks/hacks/IPython%20Parallel%20and%20R

**Comment by przell** [comment]
Dask and Rpy2:
https://github.com/dask/distributed/issues/2119
https://github.com/dask/dask-examples#contributing
https://github.com/jmcarpenter2/swifter/issues/62

**Comment by flahn** [comment]
Regarding stack imbalance:
https://stackoverflow.com/questions/42119609/how-to-handle-mismatching-in-calling-convention-in-r-and-c-using-rcpp
https://stackoverflow.com/questions/6779530/what-is-a-stack-imbalance

**Comment by przell** [comment]
@m-mohr, should we remove parallelization completely from the master and pip released version and keep it only in a branch?

**Comment by clausmichele** [comment]
I put here the code of the first test with parallelization using joblib. Next iteration would be to try using Dask directly instead of joblib. I don't have time to include it as a test in the repo at the moment. You can run it as is if you have the required libraries.

```python
import xarray as xr
import numpy as np
import datetime
import time

from openeo_r_udf import udf_lib
from openeo_r_udf.udf_lib import chunk_cube
from openeo_r_udf.udf_lib import combine_cubes
from openeo_r_udf.udf_lib import create_dummy_cube

from joblib import Parallel
from joblib import delayed as joblibDelayed

def compute_udf(data):
    return udf_lib.execute_udf(process='reduce_dimension',
                                          udf='https://raw.githubusercontent.com/Open-EO/openeo-udf-python-to-r/demo/udfs/reduce_bfast.R',
                                          data=data.compute(),
                                          dimension='t',
                                          udf_folder='./udfs/',
                                          context={'start_monitor': 2018})

# Data Cube config
dims = ['x', 'y', 't', 'b']
sizes = [1000, 1000, 260, 1]
base = datetime.datetime(2016, 1, 1)
t_labels = np.array([base + datetime.timedelta(weeks=i) for i in range(260)]).astype(str)
labels = {
    # x and y get generated automatically for now (todo: get from actual data)
    'x': None,
    'y': None,
    't': t_labels,
    'b': ['b1']
}
chunk_size = 100

# Prepare data
input_data = create_dummy_cube(dims, sizes, labels)
input_data_chunked = chunk_cube(input_data,size=chunk_size)

# Run UDF in parallel
start = time.time()
results = Parallel(n_jobs=-1, verbose=51)(joblibDelayed(compute_udf)(data) for data in input_data_chunked)
print('Elapsed time: {}'.format(time.time() - start))
result = combine_cubes(results)
print(result.mean())
 
```

**Comment by przell** [comment]
Thanks so much @clausmichele! 
We've tested that the parallelisation works on the Eurac Backend. We have this state as a fallback version now for creating the performance evaluation deliverable!
