### ISSUE TITLE
Context File structure

### ISSUE THREAD

**Issue by mattia6690** [Open-EO/openeo-udf-python-to-r#15]
During today's test we noticed that the `context` parameter is rather difficult to use in it's current implementation.

- The parameter appears to work only in `reduce_dimension` when multiple chunks are being addressed
- The parameter does not work with `apply`
- The context does not allow strings, right? This would be a great addition to hand the url location of the model to the UDF

**Comment by m-mohr** [comment]
run_udf only allows objects to be passed, at least that's what the schema says right now. Will check....

**Comment by m-mohr** [comment]
Can you provide an example, please?

**Comment by m-mohr** [comment]
As @mattia6690 is "gone" and I can't reproduce it right now, I'm closing this.
