### ISSUE TITLE
Dimension Names Issue

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-udf-python-to-r#17]
Currently it's hard coded that spatial dims are x and y, temporal dim is t.
It would be better to handle them dynamically by the names they actually have and assign the spatial and temporal dimensions.

**Comment by m-mohr** [comment]
Can you point me at something that indicates in xarray what type a dimension has?
The only thing that I found for temporal dimensions is that I can use the type of the coords and check whether it is datetime64.
