### ISSUE TITLE
scope of udf-setup and udf-teardown

### ISSUE THREAD

**Issue by basu26** [Open-EO/openeo-udf-python-to-r#25]
we had discussed about the scope of the helper funs udf_setup and udf_teardown. In "normal" R coding the objects defined in udf_setup for example will not available to the main udf function (e.g. load a model in setup and use it in the main udf). Currently we have worked around it with the double assignment `<<-` which makes it available globally. I think it would be nicer/cleaner to explicitly make it available to the udf function.  @flahn, @edzer 
Maybe there's also a more elegant way than setting `getModel = NULL`

```
getModel = NULL

udf_setup = function(context) {
  url1      <- 'https://github.com/Open-EO/r4openeo-usecases/blob/main/uc1-ml-landcover/models/TestModelIntensive_RF.rds?raw=True'
  getModel  <<- readRDS(gzcon(url(url1)))
}



udf_chunked = function(data,context){
  names(data)<-caret::predictors(getModel)
  data = data.frame(t(data))
  prediction <-predict(getModel, data)
  prediction = as.numeric(prediction)
  return(prediction)
  
}
```

**Comment by m-mohr** [comment]
We could use context for that.

**Comment by m-mohr** [comment]
As R is not passing vars by reference, we may stick with this and just document it in the README.

**Comment by m-mohr** [comment]
The documentation has been updated

**Comment by przell** [comment]
added a bit more explanation: https://github.com/Open-EO/openeo-udf-python-to-r/commit/8deb32014d7b603b55d2729a204a5a7f5a5ffea2

**Comment by m-mohr** [comment]
I had to remove parts of it, because it is incorrect. udf_setup is not present for `udf`!
