### ISSUE TITLE
Implement the code in `openeo-processes-python`

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-udf-python-to-r#3]
Port the code to the library `openeo-processes-python`. https://github.com/Open-EO/openeo-processes-python

**Comment by przell** [comment]
We'd need to integrate run_udf() for the according openEO cube processes in `openeo-processes-python`: 
For reduce for example here: https://github.com/Open-EO/openeo-processes-python/blob/master/src/openeo_processes/cubes.py#L329

**Comment by m-mohr** [comment]
The repo will get deprecated
