### ISSUE TITLE
Add real-world UDF example

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-udf-python-to-r#5]
UC2 from R4openEO would be suitable. 
- Load_collection: Sentinel 2 Time series
- Calc_ndvi: Calculate the ndvi
- UDF: Reduce_dimension along time dimension and use e.g. bfast as the reducer.

**Comment by przell** [comment]
@m-mohr, we need the time labels for bfast... can we access them within reduce_dimension along t?
I've added a code for testing here: https://github.com/Open-EO/openeo-udf-python-to-r/blob/main/udfs/reduce_bfast.R

**Comment by m-mohr** [comment]
I was thinking about something like this: https://github.com/Open-EO/openeo-udf-python-to-r/blob/bfast/udfs/reduce_bfast.R

But stars doesn't seem to provide any labels...

**Comment by przell** [comment]
Load openEO data cube and insert in test_bfast.py, to run on real openEO data cube

**Comment by przell** [comment]
this is solved with demo.py and the bfast process on ndvi data from vito
