### ISSUE TITLE
Create environment.yaml so that python, R and rpy2 run in one env without leaving it

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-udf-python-to-r#6]
# minimal env
Should be possible to run rpy2 within a single conda env: https://stackoverflow.com/questions/42126077/use-rpy2-with-packages-installed-for-r-in-conda-virtual-environment

# use case env (typical for backends to deploy)
add also all typical r packages that you want to have supported

**Comment by m-mohr** [comment]
R requirements:

- jsonlite
- lubridate
- stars
